"use client";
import { Plus_Jakarta_Sans, Public_Sans } from "next/font/google";
import { Providers } from "./providers";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.bundle.min";
import "./globals.css";
import "line-awesome/dist/line-awesome/css/line-awesome.min.css";
import Navbar from "@/components/common/nav/Navbar";
import Footer from "@/components/common/nav/Footer";
import Footertwo from "@/components/common/nav/Footertwo";
import { usePathname } from "next/navigation";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const path = usePathname();
  return (
    <html lang="en">
      <body className={`${plusJakarta.variable} ${publicSans.variable}`}>
        <Providers>
          <Navbar />
          {children}
          {path === "/" ? <Footer /> : <Footertwo />}
          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  );
}
